### ISSUE TITLE
Update Development Guide on AutoExpenditure

### ISSUE THREAD

**Issue by SwampertX** [AY1920S1-CS2103-T16-4/main#125]
A checklist for my own reference.

- [x] Subheader 1  - Implementation
  - [x] textual description about implementation
  - [x] usage scenario
  - [x] sequence diagram
  - [ ] activity diagram
- [x] Subheader 2 - Design Considerations
  - [x] Aspect 1
    - [x] Alternative 1
    - [x] Alternative 2 (Current choice)
- [x] ...

**Comment by SwampertX** [comment]
Update only when #94, #95 and #96 are done.

**Comment by Dandford** [comment]
Moved to 1.4

**Comment by SwampertX** [comment]
Closed by #181 .
