### ISSUE TITLE
Update UI section in DG

### ISSUE THREAD

**Issue by jessicax941** [AY1920S1-CS2103-T16-4/main#146]
- [x] update UI class diagram

* Toggle panel command
- [x] partial class diagram for side panels
- [x] update implementation for toggle panel command 
- [x] update ToggleSequenceDiagram
- [x] update ToggleActivityDiagram

* Change font command
- [x] add ChangeFontSequenceDiagram
- [x] changeFont activity diagram
- [x] add implementation for change font

* Set dark/light theme
- [x] set dark/light theme implementation
- [x] set dark/light theme sequence diagram
- [x] set dark/light theme activity diagram

**Comment by Dandford** [comment]
Moved to 1.4
